### ISSUE TITLE
Error: Dependencies are still missing after setup even though the setup completed successfully

### ISSUE THREAD

**Issue by s0yi** [CosmicScale/PSBBN-Definitive-English-Patch#217]
I’m stuck with the installation it keeps saying some dependencies are missing

Setup log

Installing Dependences:
Hit:1 http://security.ubuntu.com/ubuntu noble-security InRelease
Hit:2 http://archive.ubuntu.com/ubuntu noble InRelease
Hit:3 http://archive.ubuntu.com/ubuntu noble-updates InRelease
Hit:4 http://archive.ubuntu.com/ubuntu noble-backports InRelease
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
axel is already the newest version (2.17.13-1build2).
imagemagick is already the newest version (8:6.9.12.98+dfsg1-5.2build2).
xxd is already the newest version (2:9.1.0016-1ubuntu7.8).
python3 is already the newest version (3.12.3-0ubuntu2).
python3-venv is already the newest version (3.12.3-0ubuntu2).
python3-pip is already the newest version (24.0+dfsg-1ubuntu1.2).
nodejs is already the newest version (18.19.1+dfsg-6ubuntu5).
npm is already the newest version (9.2.0~ds1-2).
bc is already the newest version (1.07.1-3ubuntu4).
rsync is already the newest version (3.2.7-1ubuntu1.2).
curl is already the newest version (8.5.0-2ubuntu10.6).
unzip is already the newest version (6.0-28ubuntu4.1).
wget is already the newest version (1.21.4-1ubuntu4.1).
chromium-browser is already the newest version (2:1snap1-0ubuntu2).
ffmpeg is already the newest version (7:6.1.1-3ubuntu5).
lvm2 is already the newest version (2.03.16-3ubuntu3.2).
libfuse2t64 is already the newest version (2.9.9-8.1build1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
[✓] Packages checked/installed.
[✓] Setting up Python virtual environment and installing dependencies...
[✓] Installing Puppeteer via npm...
[✓] Puppeteer installed successfully.

[✓] Setup completed successfully!

[X] Error: Dependencies still missing after setup.

**Comment by s0yi** [comment]
[setup.log](https://github.com/user-attachments/files/22030270/setup.log)

**Comment by BEnh3N** [comment]
I had this issue too, cloning the repo again fixed it for me

**Comment by CosmicScale** [comment]
> I had this issue too, cloning the repo again fixed it for me

A lot has changed, so it’s possible that `git fast-forward` didn’t work correctly. If anyone encounters issues, run the following commands to delete and re-clone the repository, then run the script. Make sure to back up any games or apps you have in `PSBBN-Definitive-English-Patch/games` first!:
```
cd
rm -rf PSBBN-Definitive-English-Patch
git clone https://github.com/CosmicScale/PSBBN-Definitive-English-Patch.git
cd PSBBN-Definitive-English-Patch
./PSBBN-Definitive-Patch.sh
```

**Comment by CosmicScale** [comment]
> I’m stuck with the installation it keeps saying some dependencies are missing

Just tried on a fresh install of Ubuntu 24.04.3 LTS, works perfectly for me.

**Comment by s0yi** [comment]
> > I’m stuck with the installation it keeps saying some dependencies are missing
> 
> Just tried on a fresh install of Ubuntu 24.04.3 LTS, works perfectly for me.

I managed to get past the error by installing Debian but now I’m stuck at ‘Installing PSBBN’ I didn’t have any issues with the previous version (v2.11)

[PSBBN-installer.log](https://github.com/user-attachments/files/22032394/PSBBN-installer.log)

**Comment by CosmicScale** [comment]
I've just pushed an update. Give it another try.

**Comment by s0yi** [comment]
[PSBBN-installer.log](https://github.com/user-attachments/files/22032856/PSBBN-installer.log)

Do you wish to proceed? (y/n): y

Installing PSBBN...
[X] Error: Partition __linux.1 not found on disk.

Press any key to return to the menu...

**Comment by CosmicScale** [comment]
Just installed with the same version of Debian, no problems on my end. I don't know what your issue could be.

**Comment by miriamburgers** [comment]
I'm also having the "Dependencies are still missing after Setup" error. Does not get fixed by deleting and re-cloning, sadly. The previous version worked with no issues here as well.

[setup.log](https://github.com/user-attachments/files/22033265/setup.log)

**Comment by GoatWalker** [comment]
I'm using WSL and was having the same issue, until I did the commands you suggested.

**Comment by CosmicScale** [comment]
> I'm also having the "Dependencies are still missing after Setup" error. Does not get fixed by deleting and re-cloning, sadly. The previous version worked with no issues here as well.

Weird that you're getting that error for chromium. What happens if you run this command?
```
command -v chromium
```

**Comment by wisepass2000** [comment]
I'm using Windows 10 initially recent WSL Debian (though I note I did have issues installing directly from the Microsoft store (stuck at 0% bug) 
I also had to re-clone the repository as above as I got following error when I ran ./PSBBN-Definitive-Patch.sh after selecting drive media sizes..
> [X] Error: Failed to create filesystem __linux.8.

gives some more details in PSBBN-installer.log 
> /home/pi/PSBBN-Definitive-English-Patch/scripts/helper/mkfs.vfat: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.38' not found (required by /home/pi/PSBBN-Definitive-English-Patch/scripts/helper/mkfs.vfat)
[X] Error: Failed to create filesystem __linux.8.

I also tried with fresh installs of ubuntu, but this gave a different puppeteer error on install. 

In Powershell(as admin) I tried unregistering and deleting Debian 
`wsl --unregister Debian`
updated wsl 
`wsl --update --web-download`
Reinstalled Debian 
`wsl --install Debian --web-download`

Things looked more promising running ./PSBBN-Definitive-Patch.sh - I had to remount the USB drive before install as you might expect.

"Do you wish to proceed? (y/n): y

Installing PSBBN...

Running APA-Jail...
> [X] Error: Failed to create /home/pi/PSBBN-Definitive-English-Patch/scripts/storage/OPL.

Checked PSBBN-installer.log 
> mkdir: cannot create directory ‘/home/pi/PSBBN-Definitive-English-Patch/scripts/storage/OPL’: Permission denied
[X] Error: Failed to create /home/pi/PSBBN-Definitive-English-Patch/scripts/storage/OPL.

exited installer and created above from command prompt. (with sudo)
`sudo mkdir /home/pi/PSBBN-Definitive-English-Patch/scripts/storage/OPL`

re-ran the installer again...option 1
`./PSBBN-Definitive-Patch.sh`

[✓] PSBBN successfully installed.

**Comment by CosmicScale** [comment]
I've removed the chromium dependency as Puppeteer uses its own version.

**Comment by CosmicScale** [comment]
> I'm using Windows 10 initially recent WSL Debian

I have also used Windows 10 and WSL Debian this evening and had no problems installing PSBBN. Unfortunately, I really don't know what I can do to help.

**Comment by CosmicScale** [comment]
> sudo mkdir /home/pi/PSBBN-Definitive-English-Patch/scripts/storage/OPL

The script creates that directory on your PS2 drive. Running that after the script completed would create the folder on your PC as the drive would most likely not be mounted.

**Comment by CosmicScale** [comment]
> mkdir: cannot create directory ‘/home/pi/PSBBN-Definitive-English-Patch/scripts/storage/OPL’: Permission denied
> [X] Error: Failed to create /home/pi/PSBBN-Definitive-English-Patch/scripts/storage/OPL.

I've now made some changes to how directories are make with commit https://github.com/CosmicScale/PSBBN-Definitive-English-Patch/commit/4882b4147d1e1f6b319de96cc80fc8055e0952b5 so give it another try.

**Comment by CosmicScale** [comment]
> > mkdir: cannot create directory ‘/home/pi/PSBBN-Definitive-English-Patch/scripts/storage/OPL’: Permission denied
> > [X] Error: Failed to create /home/pi/PSBBN-Definitive-English-Patch/scripts/storage/OPL.
> 
> I've now made some changes to how directories are made with commit [4882b41](https://github.com/CosmicScale/PSBBN-Definitive-English-Patch/commit/4882b4147d1e1f6b319de96cc80fc8055e0952b5) so give it another try.

**Comment by apollonianTears** [comment]
I've also had a similar issue with the Dependencies Missing After Setup Error while on Arch. I checked the logfile to see what was the issue. Tried installing puppeteer via npm separately and updating/recloning the installer, neither of which seemed to have worked. 

[setup.log](https://github.com/user-attachments/files/22035200/setup.log)

**Comment by CosmicScale** [comment]
> I've also had a similar issue with the Dependencies Missing After Setup Error while on Arch. I checked the logfile to see what was the issue. Tried installing puppeteer via npm separately and updating/recloning the installer, neither of which seemed to have worked.

That's strange. The only thing that changed is the directory that puppeteer is installed in. It's now `scripts/node_modules`. Have you tried deleting the `PSBBN-Definitive-English-Patch` folder and re-cloning?

**Comment by miriamburgers** [comment]
> I've removed the chromium dependency as Puppeteer uses its own version.

This seems to have fixed it for me after deleting and re-cloning! Tested command -v chromium as well and it did nothing which I suppose must have been the issue.

**Comment by CosmicScale** [comment]
> Tried installing puppeteer via npm separately and updating/recloning the installer, neither of which seemed to have worked.

The setup script installs puppeteer as follows, make sure you are in the `PSBBN-Definitive-English-Patch`  and run:
```
cd ./scripts
npm install puppeteer
```
What happens when you run that manually?

**Comment by CosmicScale** [comment]
Okay, I've changed the way puppeteer is checked with commit https://github.com/CosmicScale/PSBBN-Definitive-English-Patch/commit/8867e1c5d4d9efacba64eeaa324aa9c750162391. I think the previous check just doesn't work on some distros.

**Comment by wisepass2000** [comment]
Did new install on wsl Debian and works for me without errors thanks CosmicScale!

**Comment by CosmicScale** [comment]
Okay, I think this one can be closed as it seems to be working for everyone now. Thanks for all the reports.

**Comment by its-jockel** [comment]
I had the same error on Pop! OS (debian based, cosmic desktop), and just wanted to add that installing fdisk solved my issue.

**Comment by CosmicScale** [comment]
> I had the same error on Pop! OS (debian based, cosmic desktop), and just wanted to add that installing fdisk solved my issue.

That's strange. The scripts use `sfdisk`, which is part of `util-linux` and is installed by the setup script. What command did you use to install `fdisk`?

**Comment by its-jockel** [comment]
> That's strange. The scripts use `sfdisk`, which is part of `util-linux` and is installed by the setup script. What command did you use to install `fdisk`?

sudo apt install fdisk

IDK maybe Pop! does something funky or uses other tools? The log just said missing command: sfdisk so I looked into that.
Edit: I'm really new to linux, if that clears things up

**Comment by CosmicScale** [comment]
Could you share your `setup.log` file? I'll hopefully be able to see why it failed to install sfdisk. It should work, even on Pop! OS. I'm baffled tbh.

**Comment by its-jockel** [comment]
> Could you share your `setup.log` file? I'll hopefully be able to see why it failed to install sfdisk. It should work, even on Pop! OS. I'm baffled tbh.

certainly.

[setup.log](https://github.com/user-attachments/files/24374453/setup.log)

**Comment by CosmicScale** [comment]
Okay, setup ran and it tried to install `util-linux` but it was already installed so it was skipped. 
```
util-linux is already the newest version (2.39.3-9ubuntu6.4).
```

`sfdisk` should have been installed as part of `util-linux`. Not sure why it was missing. It could have somehow got deleted or maybe it wasn't listed in your path so it could not be found. Normally installing `sfdisk` separately should not be necessary.

Anyway, glad you found the solution. Hope you enjoy PSBBN, and Linux. Don't forget to check out PS2 Linux too!
